ba_transformation:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER')}}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      database: BRITISH_AIRWAYS_DB
      schema: MARTS
      threads: 10
      warehouse: COMPUTE_WH
      client_session_keep_alive: False
      query_tag: github_action_query
