# name: Job

# on:
#   push:
#     branches:
#     - main
#   pull_request:
#     branches:
#     - main
#   schedule:
#   - cron: '0 0 * * *' # Every day at 00:00 UTC
#   workflow_dispatch:


# env:
#   SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
#   SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
#   SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
#   SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
#   SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

# jobs:
#   ba_transformation:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Get current timestamp
#       id: timestamp
#       run: echo "time=$(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT

#     - name: Checkout Code
#       uses: actions/checkout@v4

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.12'

#     - name: Install requirements
#       run: pip install -r requirements.txt

#     - name: Install dbt dependencies
#       working-directory: ./project_dir
#       run: dbt deps

#     - name: Run dbt build
#       working-directory: ./project_dir
#       run: dbt build --profiles-dir ./

#     - name: Send email notification
#       if: always()
#       uses: dawidd6/action-send-mail@v3
#       with:
#         server_address: smtp.gmail.com
#         server_port: 465
#         username: ${{ secrets.EMAIL_USERNAME }}
#         password: ${{ secrets.EMAIL_PASSWORD }}
#         subject: "British Airways Transformation Job - ${{ job.status }}"
#         to: email
#         from: ${{ secrets.EMAIL_USERNAME }}
#         body: |
#           Job Running Status

#           The workflow has completed.

#           📅 Run Time: ${{ steps.timestamp.outputs.time }}
#           🔄 Triggered by: ${{ github.event_name }}
#           ✅ Status: ${{ job.status }}

#           📂 Repository: ${{ github.repository }}
#           🔗 Workflow Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

#           Cheers,  
#           GitHub Actions 🤖

